#include <stdio.h>

/**
* main - Each new term in the Fibonacci sequence is generated by adding
* the previous two terms. By starting with 1 and 2.
* the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
* do not exceed 4,000,000  then prints the sum of the even-valued terms.
* Return: Always with 0 (Success).
*/

int main(void)
{
	int first = 0;
	int second = 1, next = 0;
	int sum = 0;

	while (next < 4000000)
	{
		next = first + second;
		first = second;
		second = next;
		if (next % 2 == 0)
			sum += next;
	}
	printf("%d\n", sum);
	return (0);
}
